---
title: "Fermentados"
---

## Picles em conserva

### Ingredientes {.unnumbered}

- 3,6 kg de pepinos
- 12 dentes de alho
- 1 cebola
- 720 ml de vinagre branco destilado
- 720 ml de água
- 60 ml de sal
- 120 ml de açúcar
- 1 punhado de semente de coentro
- 1 punhado de grãos de pimenta-do-reino

### Modo de preparo {.unnumbered}

1. Comece lavando e secando muito bem quatro potes de vidro de aproximadamente 950 ml cada, junto com suas tampas.

2. Em seguida, corte os pepinos em quartos no sentido do comprimento e acomode-os bem apertados dentro dos potes de vidro limpos. Coloque 3 dentes de alho e cerca de 60 ml de cebola fatiada em cada pote.

3. Em uma panela, adicione o vinagre, a água, o sal, o açúcar, o coentro e os grãos de pimenta-do-reino. Misture bem com um batedor até que tudo esteja completamente dissolvido. Distribua o líquido de forma uniforme entre os quatro potes.

4. Feche bem os potes e, usando uma pinça própria para conservas, coloque-os cuidadosamente em banho-maria a 85 °C por 30 a 40 minutos.

5. Passado esse tempo, retire os potes do banho-maria com a pinça e deixe esfriar sobre um pano. Você deve ouvir um “estalo” conforme esfriam, indicando que os potes foram selados corretamente e podem ser armazenados em local fresco e escuro para conservação de longo prazo.